---

- name: Converge
  hosts: all
  become: true
  roles:
    - role: ansible-rails_app
      rails_app_name: nothing
      rails_app_git_url: https://github.com/bibliotechy/rails-nihilist
      rails_app_git_branch: main
      rails_app_prod_secret: EXTREMELY_LONG_SECRET_VALUE
      bundler_version: 2.0.1
      rails_app_bundler_configs:
        - key: "NEEDS_FLAGS"
          value: "--with-flags"
      set_pig: true
      rails_app_user_envvars:
        - {envvar: "MOO", value: "cow"}
        - {envvar: "COW", value: "moo", when: "{{ set_cow is defined and set_cow }}"}
        - {envvar: "PIG", value: "oink", when: "{{ set_pig is defined and set_pig }}"}
      httpd_status_enable: true
      mpm_module: event
  vars:
    rbenv:
      env: user
      version: v1.0.0
      default_ruby: 2.6.5
      rubies:
        - version: 2.6.5
